# Generated by Django 3.1.4 on 2021-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(match='u1models.*', path='/home/images', recursive=True)),
                ('name', models.CharField(max_length=128)),
                ('samples', models.IntegerField()),
                ('datecreated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Un1models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_created=True, blank=True)),
                ('path', models.FilePathField(match='u1models.*', path='/home/images', recursive=True)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('trdata', models.FilePathField(match='train.*', path='/home/images', recursive=True)),
                ('dateupdated', models.DateTimeField(auto_now_add=True)),
                ('hyperparams', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(match='u1models.*', path='/home/images', recursive=True)),
                ('name', models.CharField(max_length=128)),
                ('samples', models.IntegerField()),
                ('datecreated', models.DateField()),
            ],
        ),
    ]
