# Generated by Django 3.1.4 on 2021-05-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u1wnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Un1models',
            new_name='Un1model',
        ),
    ]
